services:
  emqx:
    image: emqx/emqx
    container_name: emqx
    restart: always
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8883:8883"
      - "8084:8084"
      - "18083:18083"
    volumes:
      - emqx-data:/opt/emqx/data
      - emqx-logs:/opt/emqx/log
      - ./certs:/opt/emqx/certs:ro
    environment:
      EMQX_NAME: emqx
      EMQX_ALLOW_ANONYMOUS: "true"
      EMQX_DASHBOARD__DEFAULT_USERNAME: "iot"
      EMQX_DASHBOARD__DEFAULT_PASSWORD: "iot"
      EMQX_AUTH__USER__1__USERNAME: "iot-user"
      EMQX_AUTH__USER__1__PASSWORD: "iot"
      EMQX_LISTENER__SSL__EXTERNAL__ENABLE: "true"
      EMQX_LISTENER__SSL__EXTERNAL__KEYFILE: "/opt/emqx/certs/key.pem"
      EMQX_LISTENER__SSL__EXTERNAL__CERTFILE: "/opt/emqx/certs/cert.pem"

    networks:
      mi_red:
        ipv4_address: 172.20.0.10
  publisher:
    build: ../mqtt-publisher
    container_name: publisher
    depends_on:
      - emqx
    environment:
      MQTT_BROKER: 172.20.0.10
      MQTT_PORT: 8883
      MQTT_CLIENT_ID: sensor:temperature:001
      PATIENT_ID: 001
      MEASUREMENT_TYPE: temperature
      MQTT_INTERVAL: 1000
      MQTT_TLS: true
      MQTT_USERNAME: iot-user
      MQTT_PASSWORD: iot

    networks:
      mi_red:
        ipv4_address: 172.20.0.20

  subscriber:
    build: ../mqtt-subscriber
    container_name: subscriber
    depends_on:
      - emqx
    environment:
      MQTT_BROKER: 172.20.0.10
      MQTT_PORT: 8883
      MQTT_TOPIC: uci/patients/#
      MQTT_CLIENT_ID: subscriber-console
      MQTT_TLS: true
      MQTT_USERNAME: iot-user
      MQTT_PASSWORD: iot

    networks:
      mi_red:
        ipv4_address: 172.20.0.30
    tty: true
    stdin_open: true

networks:
  mi_red:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1

volumes:
  emqx-data:
  emqx-logs:

